name: sectors_pollution_env
channels:
 - defaults
 - conda-forge
dependencies:
  - python=3.10
  - xarray=2022.11.0
  - netcdf4=1.6.2
  - gdal=3.0.2
  - rasterio=1.2.10
  - rasterstats=0.19.0
  - pip=23.1.2 
  - pip:
    - geopandas==0.13.2
    - hydra-core==1.3.0
